[workspace]
members = [
  "oauth-credentials",
  "oauth1-request",
  "oauth1-request-derive",
]

[patch.crates-io]
oauth-credentials = { path = "oauth-credentials" }
oauth1-request = { path = "oauth1-request" }
oauth1-request-derive = { path = "oauth1-request-derive" }
